name: CI/CD - Development Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: restaurant-service-develop-deploy
  cancel-in-progress: true

jobs:
  deploy-development:
    name: Deploy to Azure Development
    uses: ./.github/workflows/deploy-to-azure.yml
    with:
      environment: development
    secrets: inherit
